### ISSUE TITLE
Can't set cookie

### ISSUE THREAD

**Issue by minecraft2fun** [ShouxTech/join-roblox-game#1]
When you go to the extension's settings to set the cookie, the setting just isn't there
![image](https://user-images.githubusercontent.com/73174685/185546233-61325c1b-6c14-45b7-a90f-015273c51c6b.png)
![image](https://user-images.githubusercontent.com/73174685/185546260-8395e8e2-0494-4158-97be-6ace20c395a0.png)

**Comment by ShouxTech** [comment]
What if you try searching for 'cookie'?

**Comment by minecraft2fun** [comment]
That also does not work
